spring:
  datasource:
    username: user
    url: jdbc:postgresql://localhost:5432/kicksmarket
    password: changeit
  application:
    name: kicksmarket
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true

logging:
  level:
    org:
      springframework:
        security: TRACE